# Generated by Django 3.0.1 on 2020-08-15 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=11)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('rooms_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('phone_no', models.BigIntegerField()),
                ('grade', models.IntegerField()),
                ('description', models.TextField(max_length=140, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('floor', models.IntegerField()),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('grade', models.CharField(choices=[('non vip', 'non vip'), ('vip', 'vip')], max_length=7)),
                ('price', models.IntegerField()),
                ('number_of_bed', models.SmallIntegerField(default=1)),
            ],
            options={
                'unique_together': {('floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_children', models.PositiveSmallIntegerField(default=0)),
                ('no_of_adult', models.PositiveSmallIntegerField(default=1)),
                ('reservation_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.Customer')),
                ('hotel_reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.Hotel')),
                ('room_reserve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.Room')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserve.Location'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ManyToManyField(related_name='room_hotel', to='reserve.Room'),
        ),
    ]
