# Generated by Django 3.0.1 on 2020-08-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_hotel', to='reserve.Room'),
        ),
    ]
