# Generated by Django 3.0.1 on 2020-08-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20200815_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_hotel', to='reserve.Hotel'),
        ),
    ]
