# Generated by Django 3.0.1 on 2020-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_room',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
