# Generated by Django 3.0.1 on 2020-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_room_image_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_pics'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_room',
            field=models.ImageField(blank=True, null=True, upload_to='room_pics'),
        ),
    ]
