# Generated by Django 3.0.1 on 2020-08-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_auto_20200816_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
    ]
